/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#121416',
        'outline-variant': '#434656',
        'secondary-fixed-dim': '#c5c6cc',
        'on-secondary-container': '#b6b8be',
        'outline': '#8e90a2',
        'surface-container': '#1e2022',
        'secondary-fixed': '#e1e2e8',
        'on-primary-fixed': '#001356',
        'surface-container-lowest': '#0c0e10',
        'error-container': '#93000a',
        'on-surface-variant': '#c4c5d9',
        'tertiary-fixed-dim': '#c5c7c8',
        'on-primary': '#002388',
        'on-background': '#e2e2e5',
        'on-surface': '#e2e2e5',
        'surface-container-low': '#1a1c1e',
        'on-tertiary-fixed-variant': '#454748',
        'tertiary-fixed': '#e1e3e4',
        'on-primary-fixed-variant': '#0035be',
        'on-secondary-fixed': '#191c20',
        'primary': '#b8c3ff',
        'surface': '#121416',
        'on-error': '#690005',
        'inverse-surface': '#e2e2e5',
        'secondary': '#c5c6cc',
        'on-tertiary-fixed': '#191c1d',
        'primary-container': '#2e5bff',
        'secondary-container': '#46494e',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#dde1ff',
        'surface-variant': '#333537',
        'inverse-primary': '#124af0',
        'surface-container-high': '#282a2c',
        'on-secondary-fixed-variant': '#44474b',
        'primary-fixed-dim': '#b8c3ff',
        'inverse-on-surface': '#2f3133',
        'tertiary-container': '#6b6d6e',
        'surface-bright': '#38393c',
        'surface-tint': '#b8c3ff',
        'background': '#121416',
        'surface-container-highest': '#333537',
        'on-tertiary-container': '#eff0f1',
        'error': '#ffb4ab',
        'on-tertiary': '#2e3132',
        'on-primary-container': '#efefff',
        'tertiary': '#c5c7c8',
        'on-secondary': '#2e3135',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '40px',
        'unit': '4px',
        'gutter': '16px',
        'max-width': '1440px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-lg': ['Source Serif 4', 'serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Source Serif 4', 'serif'],
        'data-mono': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Source Serif 4', 'serif'],
        'display-lg': ['Source Serif 4', 'serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'data-mono': ['13px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
