/**
 * Export utilities for compliance reports.
 *
 * Generates downloadable Markdown and PDF files from the report data.
 */

import type { ReviewResult, ReportFinding } from './api';

// ---------------------------------------------------------------------------
// Markdown Export
// ---------------------------------------------------------------------------

/**
 * Generate a Markdown string from a compliance report.
 */
export function generateMarkdown(
  result: ReviewResult,
  fileName: string,
): string {
  const { report } = result;
  const date = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });

  const lines: string[] = [];

  // Header
  lines.push('# Compliance Review Report');
  lines.push('');
  lines.push(`**Document:** ${fileName}`);
  lines.push(`**Regulations:** ${result.regulations.map(r => r.toUpperCase()).join(', ')}`);
  lines.push(`**Generated:** ${date}`);
  lines.push(`**Session:** ${result.sessionId}`);
  lines.push('');

  // Executive Summary
  lines.push('---');
  lines.push('');
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(`**Overall Risk:** ${report.overallRisk}`);
  lines.push(`**Critical Violations:** ${report.criticalCount}`);
  lines.push(`**Warnings:** ${report.warningCount}`);
  lines.push(`**Passing Clauses:** ${report.passingCount}`);
  lines.push('');
  lines.push(report.summary);
  lines.push('');

  // Recommendation
  lines.push('### Recommendation');
  lines.push('');
  lines.push(`> ${report.recommendation}`);
  lines.push('');

  // Risk Matrix Table
  lines.push('---');
  lines.push('');
  lines.push('## Risk Matrix');
  lines.push('');
  lines.push('| Clause | Category | Severity | Regulation | Status | Confidence | Escalate |');
  lines.push('|--------|----------|----------|------------|--------|------------|----------|');

  for (const f of report.findings) {
    lines.push(
      `| ${f.id} | ${f.category} | ${f.severity} | ${f.regulation} ${f.article} | ${f.status} | ${f.confidence}% | ${f.humanReview ? '⚠️ YES' : '✅ No'} |`,
    );
  }
  lines.push('');

  // Detailed Findings
  lines.push('---');
  lines.push('');
  lines.push('## Detailed Findings');
  lines.push('');

  for (const f of report.findings) {
    lines.push(`### ${f.id} — ${f.category} [${f.severity}]`);
    lines.push('');
    lines.push(`**Status:** ${f.status}`);
    lines.push(`**Regulation:** ${f.regulation} — ${f.article}`);
    lines.push(`**Confidence:** ${f.confidence}%`);
    if (f.humanReview) {
      lines.push(`**⚠️ FLAGGED FOR HUMAN REVIEW**`);
    }
    lines.push('');
    lines.push('**Clause Text:**');
    lines.push(`> ${f.clauseText}`);
    lines.push('');
    lines.push('**Reasoning:**');
    lines.push(f.reasoning);
    lines.push('');
  }

  // Regulatory References
  lines.push('---');
  lines.push('');
  lines.push('## Regulatory References');
  lines.push('');

  const regCitations = report.findings.reduce<Record<string, string[]>>((acc, f) => {
    const reg = f.regulation;
    if (!acc[reg]) acc[reg] = [];
    const cite = f.article !== 'N/A' ? f.article : '';
    if (cite && !acc[reg].includes(cite)) acc[reg].push(cite);
    return acc;
  }, {});

  for (const [reg, articles] of Object.entries(regCitations)) {
    lines.push(`**${reg}**`);
    for (const art of articles) {
      lines.push(`- ${art}`);
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by RegulationGuard — Multi-Agent Compliance & Regulatory Review System*');

  return lines.join('\n');
}

/**
 * Trigger a Markdown file download in the browser.
 */
export function downloadMarkdown(result: ReviewResult, fileName: string): void {
  const md = generateMarkdown(result, fileName);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  triggerDownload(blob, `${fileName.replace(/\.[^.]+$/, '')}_compliance_report.md`);
}

// ---------------------------------------------------------------------------
// PDF Export (via HTML print)
// ---------------------------------------------------------------------------

/**
 * Generate an HTML string for the compliance report, then trigger
 * the browser's print dialog which allows saving as PDF.
 */
export function downloadPDF(result: ReviewResult, fileName: string): void {
  const { report } = result;
  const date = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });

  const severityColor = (s: string) => {
    switch (s) {
      case 'CRITICAL': return '#ef4444';
      case 'MEDIUM': return '#f59e0b';
      case 'LOW': return '#10b981';
      default: return '#6b7280';
    }
  };

  const statusColor = (s: string) => {
    switch (s) {
      case 'VIOLATION': return '#ef4444';
      case 'WARNING': return '#f59e0b';
      case 'COMPLIANT': return '#10b981';
      default: return '#6b7280';
    }
  };

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Compliance Report — ${fileName}</title>
  <style>
    @page { margin: 20mm; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: #1a1a1a;
      line-height: 1.6;
      font-size: 12px;
    }
    h1 { font-size: 22px; margin-bottom: 4px; }
    h2 { font-size: 16px; margin: 24px 0 12px; border-bottom: 2px solid #e5e7eb; padding-bottom: 4px; }
    h3 { font-size: 13px; margin: 16px 0 8px; }
    .meta { color: #6b7280; font-size: 11px; margin-bottom: 16px; }
    .summary-grid { display: grid; grid-template-columns: 1fr 1fr 1fr 1fr; gap: 12px; margin: 16px 0; }
    .summary-card { border: 1px solid #e5e7eb; padding: 12px; }
    .summary-card .label { font-size: 10px; color: #6b7280; text-transform: uppercase; }
    .summary-card .value { font-size: 24px; font-weight: 700; }
    .rec-box { border: 1px solid; padding: 12px; margin: 12px 0; }
    .rec-box.high { border-color: #ef4444; background: #fef2f2; }
    .rec-box.medium { border-color: #f59e0b; background: #fffbeb; }
    .rec-box.low { border-color: #10b981; background: #f0fdf4; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 10px; }
    th, td { border: 1px solid #e5e7eb; padding: 6px 8px; text-align: left; }
    th { background: #f9fafb; font-weight: 600; }
    .badge { display: inline-block; padding: 1px 6px; font-size: 9px; font-weight: 600; border-radius: 2px; color: white; }
    .finding { border: 1px solid #e5e7eb; padding: 12px; margin: 8px 0; }
    .finding-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; }
    .flagged { color: #f59e0b; font-weight: 600; font-size: 10px; }
    .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 10px; }
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
  </style>
</head>
<body>
  <h1>Compliance Review Report</h1>
  <div class="meta">
    <strong>Document:</strong> ${fileName} &nbsp;|&nbsp;
    <strong>Regulations:</strong> ${result.regulations.map(r => r.toUpperCase()).join(', ')} &nbsp;|&nbsp;
    <strong>Generated:</strong> ${date}
  </div>

  <h2>Executive Summary</h2>
  <div class="summary-grid">
    <div class="summary-card">
      <div class="label">Overall Risk</div>
      <div class="value" style="color: ${severityColor(report.overallRisk === 'HIGH' ? 'CRITICAL' : report.overallRisk === 'MEDIUM' ? 'MEDIUM' : 'LOW')}">${report.overallRisk}</div>
    </div>
    <div class="summary-card">
      <div class="label">Critical</div>
      <div class="value" style="color: #ef4444">${report.criticalCount}</div>
    </div>
    <div class="summary-card">
      <div class="label">Warnings</div>
      <div class="value" style="color: #f59e0b">${report.warningCount}</div>
    </div>
    <div class="summary-card">
      <div class="label">Passing</div>
      <div class="value" style="color: #10b981">${report.passingCount}</div>
    </div>
  </div>

  <p>${report.summary}</p>

  <div class="rec-box ${report.overallRisk.toLowerCase()}">
    <strong>Recommendation:</strong> ${report.recommendation}
  </div>

  ${report.findings.some(f => f.humanReview) ? `
  <div class="rec-box medium">
    <strong>⚠️ Human Review Required:</strong> ${report.findings.filter(f => f.humanReview).length} clause(s) flagged for human legal counsel review.
  </div>` : ''}

  <h2>Risk Matrix</h2>
  <table>
    <thead>
      <tr>
        <th>Clause</th>
        <th>Category</th>
        <th>Severity</th>
        <th>Regulation</th>
        <th>Status</th>
        <th>Conf.</th>
        <th>Escalate</th>
      </tr>
    </thead>
    <tbody>
      ${report.findings.map(f => `
      <tr>
        <td>${f.id}</td>
        <td>${f.category}</td>
        <td><span class="badge" style="background:${severityColor(f.severity)}">${f.severity}</span></td>
        <td>${f.regulation} ${f.article}</td>
        <td><span class="badge" style="background:${statusColor(f.status)}">${f.status}</span></td>
        <td>${f.confidence}%</td>
        <td>${f.humanReview ? '⚠️ Yes' : '✅ No'}</td>
      </tr>`).join('')}
    </tbody>
  </table>

  <h2>Detailed Findings</h2>
  ${report.findings.map(f => `
  <div class="finding">
    <div class="finding-header">
      <strong>${f.id} — ${f.category}</strong>
      <span class="badge" style="background:${severityColor(f.severity)}">${f.severity}</span>
    </div>
    <p><strong>Clause Text:</strong> ${f.clauseText}</p>
    <p><strong>Citation:</strong> ${f.regulation} ${f.article} &nbsp;|&nbsp; <strong>Confidence:</strong> ${f.confidence}%</p>
    <p><strong>Reasoning:</strong> ${f.reasoning}</p>
    ${f.humanReview ? '<p class="flagged">⚠️ FLAGGED FOR HUMAN REVIEW</p>' : ''}
  </div>`).join('')}

  <div class="footer">
    Session: ${result.sessionId} &nbsp;|&nbsp; 4/4 agents completed &nbsp;|&nbsp; RegulationGuard v1.0
  </div>
</body>
</html>`;

  // Open a new window and trigger print
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    // Wait for content to render, then trigger print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
      }, 300);
    };
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
